import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Dashboard from "../components/dashboard";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Coindirect | WiiQare</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard title=""> </Dashboard>
    </>
  );
};

export default Home;
