import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coindirect | WiiQare</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the demo of{" "}
          <a href="https://www.coindirect.com">Coindirect</a> API
        </h1>

        <div className={styles.grid}>
          <a href="/currencies" className={styles.card}>
            <h2>Fiat currencies &rarr;</h2>
            <p>
              The complete list of fiat currencies supported in both payments
              and channels.
            </p>
          </a>

          <a href="/channels" className={styles.card}>
            <h2>Channels &rarr;</h2>
            <p>Create and list channels.</p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
